### PR TITLE
German

### PR DESCRIPTION
**Pull request by friesenkiwi**
Making the German language Pack available again as discussed in https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/690#issuecomment-274384088

### CODE REVIEW

**Comment by menny** [comment]
@friesenkiwi thanks for the PR.

To get it on f-droid, I have a few technical things to figure, but I'll get that done.

For Play-Store, I'll need:
1) a 1024x500 banner image (best if it's a cropped screenshot of the German keyboard).
2) translations to German of:
  * title: "German Language Pack"
  * promo: "German language pack for AnySoftKeyboard"
  * description: "AnySoftKeyboard keyboards pack:
German keyboard and dictionary.

This is an expansion pack for AnySoftKeyboard.
Install AnySoftKeyboard first, and then select the desired layout from AnySoftKeyboard's Settings->Keyboards menu."

**Comment by friesenkiwi** [comment]
Did the translations in the strings.xml and included the banner as a .png as a drawable.
Also, I cleaned up a bit and actually had to include the newly generated dictionary, had missed that before.
It's a new PR: https://github.com/AnySoftKeyboard/LanguagePack/pull/28

Here are the translations separately:

- Deutsches Sprachpaket
- Deutsches Sprachpaket für AnySoftKeyboard
- AnySoftKeyboard Tastatur-Paket: Deutsche Tastatur und Wörterbuch.
Dies ist ein Erweiterungspaket für AnySoftKeyboard.
Installiere zuerst AnySoftKeyboard und wähle dann die gewünschte Tastaturbelegung in AnySoftKeyboards Menü Einstellungen->Keyboards.

The image is at https://github.com/friesenkiwi/LanguagePack/blob/75601ef902360b233ae048731c3c40986dbfaa36/src/main/res/drawable/store_banner.png

**Comment by DerXteMensch** [comment]
Hi everyone,

the German dictionary, which just got an update on the 25th of January, has a serious bug: Since the update, the dictionary doesn't contain any words with umlauts anymore. That is a serious bug as in German we have lots of words with ä,ö,ü,ß.

Can you have a look? Thanks a lot.

Best regards

Malte.

**Comment by friesenkiwi** [comment]
Huh ... now you're saying it, it seems as if you were right. Sorry for that :-(. I seem to have so many words in my custom dictionary that it didn't occur to me earlier. @menny can you have a look on the generation task (when you're back from travelling), probably similar problems will pop up in Spanish, also in the new Swedish PR and so on?

**Comment by menny** [comment]
@friesenkiwi does `de_wordlist.combined` contain the missing words?

**Comment by friesenkiwi** [comment]
Yes, it does, e.g. 
`word=anstößigen,f=67,flags=,originalFreq=67` (line 69765, just a random example ;-))

**Comment by menny** [comment]
I see that `GenerateWordsListFromAOSPTask` fails to get any accent characters... or most of them.
It's is a problem, ah..

**Comment by menny** [comment]
Seems like we'll need to republish the Swedish and German packs. I'll do that, no need for a new PR.

I'll update the _master_ branch here to make sure it uses a fixed AOSP generate task.

**Comment by friesenkiwi** [comment]
Ah, OK.
I made some additional changes to the German one to cater for the questions over in https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/690. There are two new keyboards in there now. If there has to be a republish anywhere, we could just slip them in? I already pushed to https://github.com/friesenkiwi/LanguagePack/tree/German, so a PR would be easy.

**Comment by menny** [comment]
I see, then please create a new PR for the German pack with your changes. Please rebase it against master as well.

**Comment by friesenkiwi** [comment]
Ok, will do, just a moment

**Comment by friesenkiwi** [comment]
Ok, did it (https://github.com/AnySoftKeyboard/LanguagePack/pull/30), but it says "conflicts", I hope everything works this way? I'm really feeling uncomfortable with rebasing and force-pushing... I'm more familiar with merging, feels as if that's not so susceptible to conflicts...?

**Comment by menny** [comment]
Okay, I see your point. Can you change the PR to only include your changes? And I'll rebase and bump the version before publishing

**Comment by friesenkiwi** [comment]
I hope I can... :) will take me some minutes

**Comment by friesenkiwi** [comment]
Ok, seems it worked :)

**Pull request merged**
