### PR TITLE
Tifinagh

### PR DESCRIPTION
**Pull request by DanShai**
Tifinagh language for AnySoftKeyboard

### CODE REVIEW

**Comment by menny** [comment]
sorry for taking so long.
This is amazing

**Comment by menny** [comment]
Can you provide an icon for the language pack?

**Comment by DanShai** [comment]
I ll do it this weekend !

**Comment by menny** [comment]
@DanShai ping. About the images

@friesenkiwi can you check this out as well?

**Comment by menny** [comment]
Also, this language pack PR should point to `Tifinagh` and not `master`

**Comment by DanShai** [comment]
Hi Menny sorry I ve been busy. yes I realised the PR conflict! I ill try to make the icons as soon as possible !

**Comment by friesenkiwi** [comment]
Also, there were earlier efforts by @BoFFire for Tifinagh and Kabyle packs (see https://github.com/AnySoftKeyboard/LanguagePack/issues/54, https://github.com/AnySoftKeyboard/LanguagePack/pull/58, https://github.com/AnySoftKeyboard/LanguagePack/issues/41). Unfortunately, due to the small hiatus, she seems to have dropped them now and deleted the repos here on Github :-(
Maybe it is possible to team up and resurrect those? It is definitely disirable to have good packages for both languages!

**Comment by friesenkiwi** [comment]
Closing this in favor of #75.

**Pull request closed without merging**
