### PR TITLE
adding french - azerty accents layout

### PR DESCRIPTION
**Pull request by PhieF**
This layout gives priority to French accents as does AOSP keyboard

ref
https://github.com/AnySoftKeyboard/LanguagePack/issues/138

### CODE REVIEW

**Comment by menny** [comment]
thank you, @PhieF 
Can you attach a screenshot of the new layout?

**Comment by PhieF** [comment]
The main differences are on a and e
IMG_20190404_152627
IMG_20190404_152646

**Comment by menny** [comment]
I will release shortly.

**Comment by PhieF** [comment]
Hi, after using it a bit more I'd like to make a small correction to the "-" should I create a new pull request ?

**Pull request merged**
