### PR TITLE
Migrating Tamazight

### PR DESCRIPTION
**Pull request by menny**

### CODE REVIEW

**Comment by menny** [comment]
@BoFFire can you take a look at this?

**Comment by BoFFire** [comment]
Happy new berber amazigh year !
Aseggas Ameggaz, ⴰⵙⴻⴳⴳⴰⵙ ⴰⵎⴻⴳⴳⴰⵣ.

It could be nice if this is released for tomorrow 12 January 2019 \o/ to celebrate 🎉

**Comment by menny** [comment]
@BoFFire I'll gladly do that. Could you verify that the APK works correctly?

**Comment by BoFFire** [comment]
Hi @menny
Send links to nudes (APK) :) I do that :)

**Comment by menny** [comment]
@BoFFire here you go: https://831-4270172-gh.circle-artifacts.com/0/debug-apks/ASKLangPack-tamazight-1831.apk

**Comment by BoFFire** [comment]
@menny As an initial release, it's nice :) Thank you !
I'll improve some missing aspects (16 keys keypad layout, for example) little by little as issues will be submitted by users.
Will be nice if available in both Google Play and F-Droid :) Waiting for it.

**Comment by menny** [comment]
great.

@BoFFire please also go over the Play-Store listings and check if everything is fine: https://github.com/AnySoftKeyboard/LanguagePack/tree/master/languages/tamazight/apk/src/main/play

**Comment by BoFFire** [comment]
@menny nice icon and flag ok.
Need this sentence to be replaced :

`Install AnySoftKeyboard first, and then select the French keyboard from AnySoftKeyboard'…`

`Install AnySoftKeyboard first, and then select the adequate keyboard layout from AnySoftKeyboard'…`

Phone screenshots folder, need screenshots of the Tamazight Layout :)

**Comment by BoFFire** [comment]
Fixing typo https://github.com/AnySoftKeyboard/LanguagePack/pull/219

**Comment by BoFFire** [comment]
Phone screenshots for Google Play updated https://github.com/AnySoftKeyboard/LanguagePack/pull/220

**Pull request merged**
