### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ikocevski**

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Why are the license and source description no longer necessary?

**Comment by ikocevski** [comment]
I just thought since other branches don't have these they're unnecessary... but OK, I'll put them back.

**Comment by ikocevski** [comment]
It's okay now.
BTW it's been quite a while and I can't see the language pack on F-Droid. Is it on hold or something?
Also, before you merge this, should I remove the Google Play Store links from the readme files.. thought I saw you talking that you don't publish to it?

**Comment by friesenkiwi** [comment]
I don't know, why the new packs/updates (we touched 5 language packs) are not yet available through F-Droid :-( The Merge Request was merged 6 days ago. I just asked them again (https://gitlab.com/fdroid/fdroiddata/merge_requests/2405), maybe it's a problem in the build pipeline. I think they are working quite heavily on a lot of basic functionality currently.
No, the Play Store links are fine as well. The new packs, including Macedonian are not yet on the Play Store either, but I'm sure @menny will manage that soon.

**Comment by menny** [comment]
@ikocevski @friesenkiwi I've published the first release to Google Play-Store.
It should be available in the next couple of hours here: https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.macedonian

**Comment by menny** [comment]
Future merges to this branch will be automatically published.

**Pull request merged**
