### PR TITLE
Upgraded language pack for Armenian 

### PR DESCRIPTION
**Pull request by Ngalstyan4**
Changes:

-  Uses Gradle to build instead of Ant
-  Has updated and more thorough dictionary based on Wikipedia and personal polling in Facebook messages (I will update the dictionary again later when I get more data from Facebook)
- Has one additional keyboard layout which to best of my knowledge is the most widely used layout and comes as default in many other keyboards.

Tested on:
Android: KitKat, Marshmallow and Jelly Bean
Phone: HTC Desire 626s, Samsung J5, MTC 970H

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Hi and thank you for your work!
Unfortunately, the files dictionary/wiki_00.txt and dictionary/facebook_chat_words.xml are missing and the parseArmenianWiki task is not triggered.
Can you alter accordingly?

**Comment by Ngalstyan4** [comment]
Hi, 
sorry for taking so long, I had little access to internet these days.

I can add dictionary/wiki_00.txt to the repo but it is all of Armenian content of Wikipedia and is over 400M. It seems other language packs also did not include source language files even when they are referred from build.gradle (in Brazilian, e.g. dictionary/words_from_aosp.xml file is missing while it is referred from build.gradle)

The other option is to just remove the tasks and hence any references to these files.
I don't think this will cause any issues as I have the binary versions committed in the repo

Let me know which path you would like me to take.

**Comment by friesenkiwi** [comment]
We'll go without the source files. 400MB seem indeed to be a bit too much...

**Comment by Ngalstyan4** [comment]
So when will this get to production in the app?

**Comment by friesenkiwi** [comment]
I hope very soon.
I'm currently in a process to "sync" all the branches/packs and prepare a coordinated release and Armenian will be amongst those. But that's an a little bit tricky process, so it might take me another couple of weeks, I'm sorry :-(

**Comment by Ngalstyan4** [comment]
No, I am not the owner of that app.

**Pull request merged**
