### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by skrzyp**
**DO NOT MERGE YET**

Finally, it happened!

But it behaves quite weirdly, the keyboard itself works well (it's just a QWERTY with important `AltGr+[acelnoszx]` accents moved to the first place, but dictionary does not load to assigned keyboard layout. I just cloned it from latest LineageOS source and parsed it by this special Gradle task to convert it.

Can you provide me a way to fix that?

Note: I'm mostly a sysadmin and C programmer - I don't know Java, I don't know Gradle neither Android Studio. I just wanted to support this project in some way and make it more comfortable to use for me and other. :)

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Thank you for your work!
I tried the pack, and for me it works: If the Polish pack is selected, word suggestion is polish as well. So everything looks good?
 
I put a preview build of this at https://fdroid.denk-nach-mcfly.de/fdroid/repo/LanguagePack-polish-release.apk and created a new Polish branch at https://github.com/AnySoftKeyboard/LanguagePack/tree/Polish. Please make successive PRs against this branch.

**Comment by friesenkiwi** [comment]
Hey @skrzyp, any news on this? We would love to release your polish pack. Can you merge the latest changes in master and have a look at the icon? It can be generated automatically now, if you like.

**Comment by scadu** [comment]
I use the package provided in https://github.com/AnySoftKeyboard/LanguagePack/pull/70#issuecomment-313937782 with no issues so far.

**Comment by friesenkiwi** [comment]
@scadu so the issue reported by @skrzyp (

> dictionary does not load to assigned keyboard layout

) is not there for you as well?

**Comment by scadu** [comment]
@friesenkiwi I didn't notice such issue. 
See screenshot linked below
https://ptpb.pw/kFYD

**Comment by scadu** [comment]
@friesenkiwi I'm using the apk you provided for almost three months with no issues. Would it be possible to merge this one? If not, what would be the further step required? I assume that maintainter is needed.

**Comment by friesenkiwi** [comment]
@scadu, sorry for the late reply, please see over at #104

**Comment by friesenkiwi** [comment]
Closed in favor of #104

**Pull request closed without merging**
