### PR TITLE
Add Macedonian keyboard [WIP]

### PR DESCRIPTION
**Pull request by ikocevski**

### CODE REVIEW

**Comment by ikocevski** [comment]
This is step 14.. my bad.

**Comment by ikocevski** [comment]
@menny Can this pull request be re-routed to the Macedonian branch on your repo? If not, I'll make another request.

**Comment by friesenkiwi** [comment]
Yes, actually I just discovered, that contrary to my earlier belief, this is possible by using the "Edit" button in the top right corner :-)
So, the target branch was switched.

**Comment by friesenkiwi** [comment]
Regarding your empty wordlist issue, on first sight, everything looks correct to me, so it is up to @menny to find out, what the problem may be :-)
But I'll also try to build myself and see if I can find any hint.

**Comment by ikocevski** [comment]
Thank you, waiting for a solution :)

**Comment by friesenkiwi** [comment]
Actually, for me the build works fine :-)

```
Parsing 2 files for a maximum of 2147483647 words, and writing into '[...]/LanguagePack/dictionary/words_from_texts.xml'.
Reading input file [...]/LanguagePack/dictionary/wordlist.txt...
.0%..3%..6%..9%..12%..15%..18%..21%..24%..27%..30%..33%..36%..39%..42%..45%..48%..51%.Done.
Have 83255 words so far.
Reading input file [...]/LanguagePack/dictionary/conversations.txt...
.0%.Done.
Have 84012 words so far.
Sorting list...
Creating output XML file...
Wrote 84012 words.
Done.
:mergeAllWordLists
Merging 1 files for maximum 100000 words, and writing into 'words_merged.xml'. Discarding 0 words.
Reading words_from_texts.xml...
Loaded 84012 words in total...
Sorting list...
Creating output XML file...
Wrote 84012 words.
Done.
:makeDictionary
Reading words from input [...]/LanguagePack/dictionary/words_merged.xml
Will store output files under [...]/LanguagePack/src/main/res/raw. Created raw folder? false
Deleting previous versions...
Nodes = 1006461
Dict Size = 1305055
Writing to dict file [...]/LanguagePack/src/main/res/raw/words_1.dict
Writing to dict file [...]/LanguagePack/src/main/res/raw/words_2.dict
Done. Wrote 2 files.
```

I put a preview APK at https://fdroid.denk-nach-mcfly.de/fdroid/repo/ASKLangPack-macedonian-v1.0(1)-release.apk, please check.

**Comment by dimztimz** [comment]
@ikocevski can you open the issue tracker in the fork?

**Comment by friesenkiwi** [comment]
@dimztimz Why not continue commenting here...?

**Comment by ikocevski** [comment]
@friesenkiwi It's my computer's fault, something configured wrong.. never mind if it works it's okay.
@dimztimz Why, something wrong? Say it here ;)

**Comment by friesenkiwi** [comment]
Yes, to me all look good, but please check the preview APK if everything behaves and looks like supposed to. Also, could you resolve the merge conflicts? We worked a bit on the build process and the general icon. You can keep the one you made if you want, but maybe it is worth using the new automatic icon generation process.

**Comment by dimztimz** [comment]
I have some language specific comments and suggestions regarding the dictionary. I prefer to discuss them in the native language.

**Comment by ikocevski** [comment]
@friesenkiwi Would you re-open that issue? I can't.

**Comment by friesenkiwi** [comment]
I think, she/he asks you to open the issue tracker over at https://github.com/ikocevski/LanguagePack/issues ? (For me, it would be perfectly OK if you discuss those things here in different languages... )

**Comment by ikocevski** [comment]
@friesenkiwi Thanks, I'm a bit dumb.
@dimztimz Go for it.

**Comment by ikocevski** [comment]
@friesenkiwi The dictionary looks OK by me. There are some final touches to be added and more text files before I'd like it to be released. Might be more than final touches as I've learned through the making though :D 
Also, should I put the wordlist.txt in the `task parseAospForEnglishDictionary` ?
Maybe this way it doesn't derive frequency from the regular list of words?

**Comment by friesenkiwi** [comment]
OK, that's good to hear. Take your time, we'll hold this PR until you're satisfied.
No, the `GenerateWordsListFromAOSPTask` tasktype is only for the specific dictionary format used in the AOSP project (including frequencies), so that won't help you here. I think, it is perfectly OK that the words from `wordlist.txt` are included with a (very low) frequency.

**Comment by ikocevski** [comment]
> Also, could you resolve the merge conflicts? We worked a bit on the build process and the general icon. You can keep the one you made if you want, but maybe it is worth using the new automatic icon generation process.

@friesenkiwi Do I have to change everything all over again? I see a lot of changes (from the recent commits). As far as I know I will need to add every change manually, right?

**Comment by friesenkiwi** [comment]
@ikocevski no, you don't have to apply every change/commit manually!
You can do it quite comfortably in Android Studio for example, or manually on the command line.
Just merge the master branch to your Macedonian branch. You will end up with the 4 conflicts shown here in the PR. The app_icon.png are quite easy to solve: Just accept "theirs". The README should be quite easy to merge as well. The build.gradle might need some closer looks, but shouldn't be much of a problem either.

In the end, you need to commit the changes you made during merge, to finalize the merge.
And that's it.
As said, I like the way Android Studio manages and displays all this, it is a great UI. But it can all be done manually as well.

**Comment by dimztimz** [comment]
@ikocevski 

Run the following locally

    git checkout master
    git pull https://github.com/AnySoftKeyboard/LanguagePack.git master
    git checkout Macedonian
    git merge master

(the first two commands update your local master, the second two merge master into Macedonian)
Now resolve the conflicts, the syntax is
```
<<<<<<
Current branch changes
=====
Other branch changes that gets merged into current
>>>>>
```

Once you edit the files,

    git add .
    git commit
    git push

**Comment by ikocevski** [comment]
@dimztimz The life saver 💯

**Comment by ikocevski** [comment]
@friesenkiwi Totally have no idea what I'm doing. Might as well just start over.

**Comment by ikocevski** [comment]
@friesenkiwi You might have a mistake in your readme. Step 9 should be src/**main**/svg-png/ or something like that... I think.

**Comment by friesenkiwi** [comment]
OK, great, thank you very much!
I made some after-merge changes, also the preview file is here: ASKLangPack-macedonian-v1.0.469(469)-release.apk.
Also you were right, I fixed the README error.
The pack is waiting for inclusion in F-Droid at https://gitlab.com/fdroid/fdroiddata/merge_requests/2405

**Pull request merged**
