### PR TITLE
New pack: Polish (ver 2)

### PR DESCRIPTION
**Pull request by mgoral**
Hi,

this is my take on adding Polish language pack to ASK. Inspired by @skrzyp work (PR #70), I created a pack which I believe is more polished (no pun intended ;)).

It includes: 

* AOSP dictionary + custom web-crawled words
* Standard Polish keyboard layout with symbols and without accented characters
* autotext with common mistakes
* scripts for re-creating a custom word list

It works on my machine and although I tried to develop everything by the book, I'm still Android noob so there might be some silly mistakes.

Beside my commit, this PR merges master to Polish branch.

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Hey @mgoral thank you very much for your contribution! On first sight here on Github, it looks very promising. Does it include all the things @skrzyp did in #70 , so is it an alternative and #70 should be closed? It would be a shame, not to recognize @skrzyp 's early contribution, which was only not merged because of missing time on our side, I am very sorry for that!
Also, @scadu asked over in the PR about the fate of this pack:
Truth is, I am currently very caught up for personal reasons and will continue to be for another three weeks, but after that I will clean up here, merge PRs and release packs, this always takes more time than originally thought.
So I am sorry again, I will not be able to release before that, I hope that's OK and you can use the time for beta testing and improvements?
I would wait with merging until than, if that's OK?

**Comment by mgoral** [comment]
Sure, no rush. I'll try to answer all your questions below.

> Does it include all the things @skrzyp did in #70 , so is it an alternative and #70 should be closed?

It includes QWERTY keyboard layout and a dictionary so yeah, it's an alternative and you'll have to choose either my PR or skrzyp's. :) It's not the same as @skrzyp's though.

1. I removed most of accented characters from the layout (skrzyp just changed their order) and left only the ones which are used in Polish. Frankly, creating good, consistent layout is harder than I thought. I thought about adding one or two alternative layouts (e.g. the one where Polish accented characters like "ę, ł, ą" are first characters on the long-press list (instead of "3, ( and @") and the one with all accented characters).

2. Dictionary contains AOSP dict words + words from analyzed Polish content (books, web pages, forums etc) + names of most popular websites in Poland (according to Alexa rank) + some additional words (currently only "AnySoftKeyboard" :)). Skrzyp only included AOSP dictionary.
.
I am not totally happy with this dictionary yet because it often displays words which I feel are inaccurate. I'd like to improve my custom text analyzer and maybe the quality of the text as well as now it includes a lot of irrelevant parts (like side menus, adverts, comment footers etc. - it is simply passed through w3m, a console web browser). I'm afraid though that I'll have to correct it manually for most of the pages.
.
BTW: should I include source texts which were parsed to create `words_nlp.xml`? These are all sites from `sites.txt` - ~200 gzipped files, ~7 MB in total, but I hope to add more of them and to improve their quality.

3. I have nicer icon (in my opinion) :P 

> It would be a shame, not to recognize @skrzyp 's early contribution, which was only not merged because of missing time on our side

I agree, although I believe that skrzyp's not responding for over 4 months didn't help either. ;) Anyway, I used his work (and other existing packs as well) to learn how things work here, but created everything from scratch (except stopwords and, obviously, AOSP dictionary). Maybe I should mention his work e.g. in README?

**Comment by ciechomke** [comment]
Few months passed and no more info in this request. To merge or not to merge, can we expect official build of this pack soon?

**Comment by ciechomke** [comment]
Also @mgoral you can also use dictionaries listed here https://sjp.pl/slownik/ort/ if you want even better dictionary.

**Comment by mgoral** [comment]
Hi, @ciechomke. I initially added all words from these dictionaries. They're great for spell checking (and they're commonly used e.g. by Libre Office AFAIK), but I find them quite horrible for keyboard with words suggestions. There are over 3 million words in SJP's dictionary, but most people know at most 30 thousand of these (source: http://sjp.pwn.pl/poradnia/haslo/;2384). Most of these 30k are known passively, i.e. people know their meaning, but they usually won't use them in a letter or conversation. Additionally, there are many, many words which most people would find strange when suggested by ASK, like "aa", "aaa", "ęsi", "ABA", "accusativu" etc. There are also many names and surnames, which also are not suitable for dictionary. While "Wałęsa" probably has its place as it's a surname of very well-known person, "Kwaśniak" or "Kowaluk" shouldn't be included in my opinion.

Also, SJP's dictionary lacks one thing which is required by ASK: words usage frequency.

So instead I decided to create custom scripts which download some popular web pages, analyze them and compare against SJP's dictionary. They also measure how often some words are used. They also consider a thing called "stopwords" - words excluded from statistics because of how frequently they're used (like "ciebie", "się", "dla", "ich", "który" etc.).

These scripts are kept in `nlp` directory on `Polish` branch. Currently they add ~2k additional words to ~180k taken from AOSP's dictionary. Both the scripts and list of downloaded sites could probably use some fine-tuning, or maybe even a pre-generated text corpus, but a) I'm not NLP specialist and b) most good corpuses cost money, especially for Polish, which is not as popular as English.

That said, I'd also love to see this PR merged and released. You can however build and install it yourself - that's how I've been using it for last few months.

**Comment by ciechomke** [comment]
@mogral Thanks for explanation. I was using this pack for few weeks and dictionary is very good.
@friesenkiwi I think that this language pack fully deserves merge & official build.

**Comment by scadu** [comment]
I agree with @ciechomke. It wouldn't hurt anyone if it was officially available language pack for sure ;)

**Comment by friesenkiwi** [comment]
Sorry for the long wait. Thank you very much for your contribution! I merge this now here and release as soon as possible!

**Comment by skrzyp** [comment]
Great!

Sorry for staying quiet, I was actually busy last year so I didn't maintained my work past the first commit. But I've read all the emails and when I've seen the new bring-up I wasn't interfering ssince you actually do a great job, far more complete than what I tried to achieve.

@friesenkiwi is the package built already? I can't find it in "releases" section, do you have some external build system for langpacks?

**Comment by friesenkiwi** [comment]
No, sorry, not deployed to Play/F-Droid yet, hopefully tonight.

**Comment by ciechomke** [comment]
@friesenkiwi Any info about F-Droid release?

**Comment by robertg042** [comment]
@friesenkiwi bumping ciechomke's question. Can't wait!

**Comment by Joppla** [comment]
@friesenkiwi 
Is there any reason why the Polish pack is not available on f-droid?

**Comment by menny** [comment]
At the moment, @friesenkiwi is extremely busy with finishing a degree and starting a new job.

**Comment by Joppla** [comment]
OK, thx for the information. 

Menny Even Danan <notifications@github.com> schreef op 8 maart 2018 14:22:20 CET:

**Comment by skrzyp** [comment]
So, can someone please provide an external host with all of these 
application binaries compiled?

**Comment by robertg042** [comment]
Or reassign this publish task to someone else (if possible and appropriate)?

**Comment by mgoral** [comment]
Hi all,

I can't upload it to neither F-Droid nor Play Store, but here's a release apk, assembled just a minute ago. You can use it if you trust me. :)

https://github.com/mgoral/dld/raw/master/ASKLangPack-polish-49-release.apk

**Comment by Joppla** [comment]
Great! Thanks for making the apk! It works well!

**Comment by scadu** [comment]
While it works I would and probably many more people thankful for having the Polish language pack available in F-droid and Play Store.
Do we know when it could be done?

On March 12, 2018 12:52:55 PM GMT+01:00, Joppla <notifications@github.com> wrote:
>Great! Thanks for making the apk! It works well!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/AnySoftKeyboard/LanguagePack/pull/104#issuecomment-372284525

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by scadu** [comment]
@menny @friesenkiwi bim bam boom. Is there any chance that @mgoral's work would land in F-droid?

**Comment by mgoral** [comment]
Hi all,
keyboard is now available on F-Droid. 😃

**Comment by Joppla** [comment]
Great! Thanks! I m happy that Polish is not with extinction threathened, than we should be maybe to lat ;-)

**Pull request merged**
