### PR TITLE
Russian pack

### PR DESCRIPTION
**Pull request by friesenkiwi**
AOSP dictionary
rebased @pelya 's fork and merged it into the resurrected SVN

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Following @pelya 's comment at https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/690#issuecomment-279337682, I now changed the aplicationId to russian2.
@menny I'd think, if both of you are OK with it, it might be easier to have the pack maintained here and the App transfered to your Google Dev account?

**Comment by pelya** [comment]
Okay for me, I'll submit a patch here if I'll do any development.

Menny, if you're okay with transferring the app to your account, I will need to know email you used for registering Google Play developer account, and a transaction ID of your $25 account registration fee, as described here:

https://support.google.com/googleplay/android-developer/answer/6230247?hl=en

You can PM them to x.pelya.x@gmail.com or through Github.

**Comment by menny** [comment]
I'll merge this once the pack ownership was transferred.

**Comment by menny** [comment]
released an update to the play-store

**Comment by menny** [comment]
fdroid: https://gitlab.com/fdroid/fdroiddata/merge_requests/2037

**Pull request merged**
