### PR TITLE
Persian language

### PR DESCRIPTION
**Pull request by AmiraliNull**
This is a good persian layout
but i don't have any experience for test and build an android app!
qwerty.xml file is correct layout for persian keyboard, but more files are not.
sorry
can you edit files for build?

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Hey, thank you very much for your contribution!
There was an old Persian pack (already on Play at https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.persian), which was due to be resurrected from SVN anyways. I now  started with it and will merge it soon, so that you can make a new PR to that branch then.

**Comment by AmiraliNull** [comment]
Previous Persian pack isn't available in iran from play store!
and that has some problems in layout!
it have better layout
and i to ask or request for publish it in F-Droid or other!

**Comment by friesenkiwi** [comment]
Yes, you are right, we do want to publish/update the Persian pack in Play and F-Droid.
And we would very much like to include your layout, either as an additional one or as a fix to the "original" one.
But I would like to use the old pack as a common base line. I just need a couple of days to uplift it here to Github, please bear with me and wait just some more days, sorry.

**Comment by AmiraliNull** [comment]
all right
thanks! :-)

**Comment by friesenkiwi** [comment]
@pi3ch it took me almost a year (really sorry for that! :-(), but now I finally merged the pack. But we can't release to Play as long as ownership hasn't been transferred as discussed in 
https://github.com/AnySoftKeyboard/LanguagePack/pull/87#issuecomment-318109867
can you come over to Gitter or contact @menny via mail or another way?

**Comment by pi3ch** [comment]
Transfer was done last year. I am on Gitter. let me know what else needed.

**Pull request merged**
