### PR TITLE
Add Serbian language

### PR DESCRIPTION
**Pull request by stefan-krle**
Hello, 

This PR adds the Serbian language pack following the instructions from the Readme file. 
Thank you for all the work on this project!

Regards,
Stefan

### CODE REVIEW

**Comment by stefan-krle** [comment]
Additional info: The added dictionary is lacking in a lot of everyday words but I plan a follow-up PR when I have time. Also, can you please publish the pack on playstore/f-droid?

Let me know if you have any feedback for the PR?

**Comment by menny** [comment]
thanks!

**Comment by menny** [comment]
@stefan-krle did you publish this pack?
I couldn't find it on the play-store, but could not create it either.

**Comment by stefan-krle** [comment]
I didn't. I asked you to publish it in the message above since it will make
it easier for people to find it.
Not sure what's the problem, did you try f-droid?

суб, 28. сеп 2019. у 20:54 Menny Even Danan <notifications@github.com> је
написао/ла:

**Pull request merged**
