### PR TITLE
Update dictionary/pt_BR_wordlist.combined

### PR DESCRIPTION
**Pull request by Luan1Carlos2**
attempt to correct dictionary error. readded the archive from AOSP

### CODE REVIEW

**Comment by menny** [comment]
@Luan1Carlos2 this is an empty dictionary

**Comment by Luan1Carlos2** [comment]
How? I've checked it. I will see it here

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by menny** [comment]
OH, I see what is happening here.
You didn't provide the actual gz file. Just the webpage. I'll fix that.

**Comment by Luan1Carlos2** [comment]
I've made another pr, this one look pretty fine

**Comment by menny** [comment]
No need for that.

**Comment by menny** [comment]
Can you try out this APK? Tell me if it works fine.
[ASKLangPack-brazilian-106-release.apk.zip](https://github.com/AnySoftKeyboard/LanguagePack/files/2727465/ASKLangPack-brazilian-106-release.apk.zip)

**Comment by menny** [comment]
You'll need to unzip it first and install on your phone.

Also, can you provide me with two screenshots of the Brazilian keyboard?

**Comment by Luan1Carlos2** [comment]
sure

**Comment by Luan1Carlos2** [comment]
It's working fine
[Imagem]


[Imagem]




________________________________

**Pull request merged**
