### PR TITLE
Add Arabic language pack

### PR DESCRIPTION
**Pull request by PromyLOPh**
Adds a custom dictionary based on the corpora used [here](https://github.com/PromyLOPh/lulua/) and three keyboard layouts (AOSP, Linux, lulua). The flag of the League of Arab Nations seems to be widely accepted as a representation for the Arabic language.

I’m not much of an Android developer, so there are certainly a few rough edges. The makeDictionary insists on having empty.txt with at least one latin letter. Not sure why.

I’m also aware of #26, but it looks like the code has been removed and thus my language pack has been built from scratch. There’s a language pack on [Google Play](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.arabic), but I can’t find it’s source code either (not in this repo or any of its branches at least).

### CODE REVIEW

**Comment by menny** [comment]
This is great. Two questions

1. compared to the language pack in the Play Store, what are the differences?
2. What is the source of the dictionary word-list?

Thanks again

**Comment by PromyLOPh** [comment]
1. I think the AOSP keyboard layout included here is slightly different from the one in the existing language pack. My main issue was the lack of source code for the existing language pack. Currently I’m developing an Arabic keyboard layout (for fun) and I wanted to use it on Android.
2. My own work, see [here](https://6xq.net/%D9%84%D8%A4%D9%84%D8%A4%D8%A9/). Basically it includes news sites, books, Wikipedia. This was the easiest way for me, since I already had the corpus. But if you prefer a different source, we can certainly replace it.

**Comment by menny** [comment]
@PromyLOPh Do you want me to merge this one and then you push the other dictionary? Or so you want to do it in this PR?

**Comment by PromyLOPh** [comment]
You mean add it additionally? What would be the benefit here? As far as
I see the number of words is capped at 300k anyway – my list has almost
4.2 million entries already.

**Comment by menny** [comment]
mostly to get a better word-frequency. But, if you think it's fine as is then let's merge it.

**Comment by PromyLOPh** [comment]
Should be fine.

**Comment by PromyLOPh** [comment]
Thanks, are packages on Google Play rebuilt from the git sources
regularly?

**Comment by menny** [comment]
they are built and published to Play Store on each merge to _master_.
But Arabic is marked as `do-not-publish` at the moment. I need to set up the play-publisher for that first.

**Comment by menny** [comment]
Hey @PromyLOPh  can you take a look at the reviews?
Rated 1 out of 5 by noora seyadi.

The new update is bad, no emoji and I hate it had to uninstall.

https://play.google.com/apps/publish?account=9112598064186436167#ReviewDetailsPlace:p=com.anysoftkeyboard.languagepack.arabic&reviewid=gp:AOqpTOFW6HniP5mU4OOtLxg5StFXcI3tJnSbOT7JzbVu87e4bbOhBqm4oeXnFqMR_Lm-yKCiWfblNrMTaT_RMsU

**Comment by PromyLOPh** [comment]
I’ve looked at the old APK and extracted the XML. Apparently it does not provide a bottom row and uses ASK’s/the user’s default then? I guess I could simply add back that emoji button? 

There’s also this review:
 ارجو من حضراتكم ، ان ترجعوا الحركات في هذا الكيبورد ... لان نحن في حاجه ماسه له !
and this one
 تحديث سيء لا يدعم تشكيل الاحرف العربية لهذا ساحذفه من جوالي.
If I understand them correctly (I’m not a native speaker), the AOSP layout also lacks Arabic diacritics. Somehow I missed that, but not having those is pretty bad, so I’ll figure out where to put them and prepare a pull request. Sorry, my bad.

**Comment by menny** [comment]
Thank you for taking the time to fix this.

Anything you can do to make our users happy 😃
If the previous layout is not part of the new pack, can you add that?
And fix anything missing in the new layouts, please.

**Pull request merged**
