### PR TITLE
Sardinian language pack files

### PR DESCRIPTION
**Pull request by asereze**
Those are all the new files for the Sardinian language pack. It should be working fine right now!

    title: "Sardu pro AnySoftKeyboard"

    promo: "Pachete pro sa limba sarda pro AnySoftKeyboard"

    description: "Pachete de tastiera pro AnySoftKeyboard: tastiera e ditzionàriu pro su sardu. Custu est unu pachete de estensione pro AnySoftKeyboard. In antis installa AnySoftKeyboard, e a pustis issèbera sa configuratzione chi cheres dae su menù de AnySoftKeyboard Impostaziones->Tastiera."

### CODE REVIEW

**Comment by asereze** [comment]
@menny I've added the three translated strings right now. Let me know if something else it's missing or if there's any problem.

**Comment by friesenkiwi** [comment]
Hi and thank you for your contribution!
I'm afraid, this dictionary also seems to become to big. The build fails on my machine because Java is out of heap.

Could you maybe use a limitation when generating the wordlist?

**Comment by asereze** [comment]
Hi @friesenkiwi, what is the limit of words your machine is able to manage? Since I created the xml files manually, I have to open them in Notepad++ and delete a group of words, so having a number could be useful. In my machine it worked fine (in the attached zip file there is the apk I get from Android Studio) so I don't know how much should I change the wordlist.

[ASKLangPack-sardinian-254-debug.apk.zip](https://github.com/AnySoftKeyboard/LanguagePack/files/2205411/ASKLangPack-sardinian-254-debug.apk.zip)

**Comment by asereze** [comment]
Hi @friesenkiwi, do you still have the same problem? What's your word limit? The language pack seems to work fine in my phone.

**Comment by menny** [comment]
@asereze Can you re-create this pack but with the new project structure?
We are no longer doing branches, but instead we have all packages as modules in one _master_ repo

**Comment by asereze** [comment]
@menny I've done it right now.

**Comment by asereze** [comment]
#209

**Comment by menny** [comment]
@asereze we can close this PR then, right? Continuing on #209

**Comment by asereze** [comment]
Yes, sure.

**Pull request closed without merging**
