### PR TITLE
adding Indonesian LanguagePack

### PR DESCRIPTION
**Pull request by azzamsa**
this is an Indonesian languagepack and dictionary.

[Indonesian LanguagePack](https://github.com/azzamsa/LanguagePack/tree/Indonesian)

Translation : 
---
###  title
Paket Bahasa Indonesia

###  promo
Paket Bahasa Indonesia untuk AnySoftKeyboard

### description
AnySoftKeyboard Paket Bahasa Indonesia : kamus dan papan ketik Indonesia

Ini adalah paket ekspansi untuk AnySoftKeyboard. pasang AnySoftKeyboard terlebih dahulu, kemudian pilih tata letak yang diinginkan dari menu AnySoftKeyboard Settings-> Keyboards.

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Thank you for the PR!
Would you like me to merge this directly or would you first like to make the changes discussed in #77?
Also, I see that Github did not recognize your account as author of the commit, probably you mistakenly used another mail address? This is not a problem, but if you'd like to connect it with your account, you can change the mail address by changing the repo settings on your machine locally, amending the last commit and force-pushing to your repo. This PR will update automatically.

After merging, we probably need another day or two to find the time to release to F-Droid and Play Store.

**Comment by azzamsa** [comment]
Yes, I am forget to do git config.username and email in this repo, because I don't use global config.

I have ammend last commit and force-pushing it. btw, how do we check that "Github did not recognize your account as author of the commit" ?

sorry, to ask this, but this is confusing me. 
in dictionary directory we have `words.xml`, `words_from_texts.xml`, `words_merged.xml`, when we use the app, which xml dictionary does the app use ?, `words.xml` or `words_from_texts.xml` or  `words_merged.xml`. because I see the preview relase just about 61.9 Kb, and the `words.xml` is more than 1 Mb. 

if the app just use `words_from_texts.xml` it is easy to remove and tidy up the word list, but if the app use `words.xml` it consist about thousand of word-lists. 

and which word-list xml dictionary  file I have to tidy up ?
I have installed the preview relase and use it since you share it, and it works good. thanks :)

**Comment by azzamsa** [comment]
After doing some research, 
I try to type 3 first letter of the words in ASK, and the result : 

- I try to type 3 first letter of these words form `words.xml` : sayumi, semerah, samples, satyawati, replacement. but ASK does not find one of them

satyawati not found

- trying words from `words_from_texts.xml` : Sahertian, contributed, jalanan &apos; . ASK find all of them.

jalanan&apos; found

- trying words from `words_merged.xml` and `popular_websites_words.xml` ASK find all of them.

**Comment by friesenkiwi** [comment]
The commit wasn't linked to your profile and didn't display your avatar when displayed here on Github web (e.g. on this page https://github.com/AnySoftKeyboard/LanguagePack/pull/78/commits/6bde77ee269ec224360440ecf4297c885bd6d030), that's how you can see if there's something wrong with the repo user.mail config. Good you were able to fix it.

The dictionaries used by Android are specified at https://github.com/AnySoftKeyboard/LanguagePack/pull/78/commits/6bde77ee269ec224360440ecf4297c885bd6d030#diff-41992629959aecfc05cf9613a5e6a57c (`@array/words_dict_array`) which points to res/values/words_dict_array.xml which in turn points (`@raw/words_1`) to res/raw/words_1.dict. The latter two files are generated during build (see build.gradle): makeDictionary (dictionary/words_merged.xml -> res/values/words_dict_array.xml + res/raw/words_1.dict) depends on mergeAllWordLists (dictionary/words_from_texts.xml + dictionary/popular_websites_words.xml -> dictionary/words_merged.xml) which depends on parseTextInputFiles (dictionary/Indonesian-slang-wikipedia.html -> dictionary/words_from_texts.xml)

So, as you already discovered yourself: words_from_texts.xml and popular_websites_words.xml are used, words_merged.xml contains both of them (as the name suggests ;-)) and words.xml currently is not used at all. It can be, though, if you include it into the inputWordsListFiles array of mergeAllWordLists in the build. gradle ;-)

The size of the .apk is not directly revealing, since an .apk is essentially a .zip (try renaming and opening with a packer).

And lastly, I wouldn't "tidy up" the xml files, but rather the sources from which they are generated (e.g. the Indonesian-slang-wikipedia.html).

**Comment by azzamsa** [comment]
@friesenkiwi Please hold this PR, I will fix and tidy up everything and make a new PR.

I will ask some questions regarding dictionary with you and others later in gitter or email,
maybe I will start at Monday and have 4 or 5 days before creating new better PR.

If I had successed, I will make a clean tutorial supplementary for readme, on how to create new languagePack, so non beginers like me can follow it easily.

I am very happy to contribute to ASK.

NB : Till sunday I still in deep village.

**Comment by azzamsa** [comment]
Hello, Good Morning.

I want to tidy up Indonesian LanguagePack and creating new PR, but before that, I have some question to ask.
I am really sorry, I am new to Android development. So I create Indonesian brach by learning other branch such Pali, German and comparing them.

1. because I am new to android development, I spent days thinking how to build such an xml dictionary, and I am wondering why, "how to built such xml dictionary" does not mentined in README file in https://github.com/AnySoftKeyboard/LanguagePack?

fortunately, After doing some google search I can find this page https://code.google.com/p/softkeyboard/wiki/BinaryDictionaries

2. if words.xml that I get from wikipedia archive as mentioned in "Where to get word-lists" section does not used by ASK, so is it mean that I can skip this proccces ?
- and is it okay for my indonesian repo not to have words.xml ?, or it is obligatory ?

3. I see ASK just us `words_from_texts.xml`, `popular_websites_words.xml`, and `words_merged.xml`. 
- popular_websites_words.xml is filled manually
- words_form_texts.xml is come from "dictionary/Indonesian-slang-wikipedia.html"
- words_merged filled by gradle.build from both of popular_websites_words.xml and words_form_texts.xml

so, the source for words_from_text.xml can be any article on wikipedia that contain indonesian language ?, it doesnt have to be indonesian-slang-article , it is right ?

(//I use Indonesian-slang article, because other branch use slang article too)

thanks.

**Comment by azispratama92** [comment]
Please upload the Indonesian database into fdroid Repo :wink:

**Comment by azzamsa** [comment]
@azispratama92 [on progress](https://github.com/AnySoftKeyboard/LanguagePack/issues/118) ... be patient :)

**Comment by azzamsa** [comment]
@friesenkiwi @menny I have updated all necessary thing, including fresh new Indonesian dictionary. ready to merge :)

**Comment by friesenkiwi** [comment]
Sorry for the long wait. Thank you very much for your contribution! I merge this now here and release as soon as possible!

**Comment by azzamsa** [comment]
Thanks :)
Happy to see you after 9 months. 
Thank you friesenkiwi .

**Pull request merged**
