### PR TITLE
Update to German pack

### LINKED ISSUE #63: German: Holding U does not default to Ü
I'm using German broad +. When I hold U the default sign is a U with ´´ on top.

### LINKED ISSUE #69: German: Großes scharfes s
Today there is a capital ß. It should be displayed instead of SS
https://unicode-table.com/de/1E9E/
http://www.n-tv.de/ticker/Scharfes-S-kommt-auch-als-Grossbuchstabe-article19912013.html

### PR DESCRIPTION
**Pull request by friesenkiwi**
* Introduces automatic deploy and Play Store details
* Fixes #69 (ẞ)
* Fixes #63 (default ü)

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Do you have high res or even better vector versions of the original icon and all the other graphics used in all the packs? I was already thinking of re-doing all the icons in high quality to have a consistent style maintained over all the packs in the stores...

**Comment by friesenkiwi** [comment]
Ok, what do you think of the new icon? :-)
As said, I would use this as a template to replace all the icons of all the packs as soon as I touch them...?

**Comment by menny** [comment]
it's great!
The icon under `src/main/res/drawable/app_icon.png` (the launcher icon) should still be 48x48 pixels :)
While you on that, want to also create launcher icon for other device resolutions?

**Comment by friesenkiwi** [comment]
@menny OK, now I use the logo generation here. What do you think, can we release?

**Pull request merged**
