### PR TITLE
Add proper README

### PR DESCRIPTION
**Pull request by ikocevski**
Please merge these readme files whenever you can and edit the links to the app stores if needed. Thanks!
Also, use the screenshots provided for the app stores if you like.

### CODE REVIEW

**Comment by friesenkiwi** [comment]
Can you maybe move the screenshots to https://github.com/AnySoftKeyboard/LanguagePack/tree/Macedonian/src/main/play/ and update the other files there?

**Comment by ikocevski** [comment]
@friesenkiwi Done ;)

**Comment by menny** [comment]
@friesenkiwi note that we still do not publish to Play-Store:
https://circleci.com/gh/AnySoftKeyboard/LanguagePack/166

**Comment by menny** [comment]
```
[ant:checkstyle] [ERROR] /opt/workspace/src/main/AndroidManifest.xml:3: You should create a new package id for your language pack, and not com.anysoftkeyboard.languagepack.languagepack. [RegexpSingleline]
[ant:checkstyle] [ERROR] /opt/workspace/src/main/AndroidManifest.xml:17: You should create a new package id for your language pack, and not com.anysoftkeyboard.languagepack.languagepack. [RegexpSingleline]
[ant:checkstyle] [ERROR] /opt/workspace/src/main/java/com/anysoftkeyboard/languagepack/macedonian/PackBroadcastReceiver.java:1: You should create a new package id for your language pack, and not com.anysoftkeyboard.languagepack.languagepack. [RegexpSingleline]
```

**Comment by friesenkiwi** [comment]
Should be fixed with https://github.com/AnySoftKeyboard/LanguagePack/commit/a8455c9dd86b2e49eec0b71b03c003c8d9c322c2

**Pull request merged**
