### PR TITLE
Update the icon of the Basque language pack

### PR DESCRIPTION
**Pull request by aldatsa**
Hi Menny,
as you know we have created a Basque language pack for AnySoftKeyboard. There were problems with the icon on the first attempt to release it (#34). A member of the Basque translation team created a new icon. It would be great if you could try to release it again. Let me know if there are any problems.

This is the title and description for the Play Store in English and Basque:

---

Basque Language pack

Features:

- Basque dictionary with more than 100,000 words that includes words from unified Standard Basque and from the Biscayan dialect. [1]
- Includes the ñ key.
- Includes the zero-width space key (a.k.a. "datraolat"). Long press the d key to use it. Useful for adding suffixes to hashtags in Twitter, Instagram...

This is an expansion language pack for AnySoftKeyboard.
Install AnySoftKeyboard first, and then select the Basque keyboard from AnySoftKeyboard's Settings -> Languages -> Keyboards menu.

[1] Note: It's based on the dictionary created by Igor Leturia for FirefoxOS. We filtered the dictionary using the spell checkers Xuxen (Standard Basque) and Xuxen B (Biscayan dialect).

---

Euskarazko hizkuntza paketea

Ezaugarriak:

- Euskara Batua eta Bizkaierazko 100.000 hitz baino gehiago dituen euskarazko hiztegia. [1]
- ñ tekla dauka.
- Zero zabalerako zuriunea tekla ("datraolat" bezala ezaguna) dauka. d tekla sakatuta edukita erabil daiteke. Erabilgarria Twitter, Instagram... eta abarretan traolei atzizkiak gehitzeko.

Hau AnySoftKeyboard-entzako hizkuntza pakete osagarri bat da.
Instalatu AnySoftKeyboard lehenik eta ondoren hautatu Euskarazko teklatua AnySoftKeyboard-en Ezarpenak -> Hizkuntzak -> Teklatuak menuan.

[1] Oharra: Igor Leturiak FirefoxOSrentzat sortutako hiztegian oinarritua dago. Xuxen (Batua) eta Xuxen B (Bizkaiera) zuzentzaile ortografikoak erabiliz iragazi dugu hiztegia.

### CODE REVIEW

**Comment by menny** [comment]
@aldatsa I'm pretty sure this will fail as well. It is still very similar to https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.hungarian&hl=en
But I'll give it a try

**Comment by aldatsa** [comment]
They accepted it :)
https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.basque

**Comment by aldatsa** [comment]
@menny I don't want to bother you but did you add the Basque translation of the description that I provided? My device is in Basque but the description of the language pack appears in English. The Basque speaking users of AnySoftKeyboard would really appreciate if you could add the translation. 

I think that you probably know how to do it, but just in case, check the "Add translations for your Store Listing" of this page:
https://support.google.com/googleplay/android-developer/answer/3125566?hl=en

**Comment by menny** [comment]
They indeed accepted it. I'm happy :)

I've set up Basque. I don't know why it doesn't show up..
screen shot 2017-02-16 at 2 57 47 pm

**Comment by aldatsa** [comment]
Thanks for the quick response Menny. We really appreciate your work.

**Comment by menny** [comment]
no worries, let me know if you want me to check anything.

**Pull request merged**
