### PR TITLE
Dutch, first official release, internal version 1.4

### PR DESCRIPTION
**Pull request by SvGeloven**

### CODE REVIEW

**Comment by SvGeloven** [comment]
Please include commit 8b94aa1 too. Thanks

**Comment by SvGeloven** [comment]
See also https://gitlab.com/fdroid/fdroiddata/merge_requests/2393 which is depending on this PR

**Comment by SvGeloven** [comment]
This PR supersedes https://github.com/AnySoftKeyboard/LanguagePack/pull/68

**Comment by friesenkiwi** [comment]
Realease/Tag is here: https://github.com/AnySoftKeyboard/LanguagePack/releases/tag/dutch-1.4

**Pull request merged**
