### PR TITLE
turkish f layout support added.

### PR DESCRIPTION
**Pull request by paledega**

### CODE REVIEW

**Comment by paledega** [comment]
Sorry for my bad commit :D

**Comment by paledega** [comment]
image

I added turkish f as default turkish layout.

**Comment by frknkrc44** [comment]
Looks good. I'll wait to merge for use it.

**Comment by paledega** [comment]
@menny pls look this

**Comment by menny** [comment]
@paledega thanks.
Please rebase your branch and force-push.

**Comment by paledega** [comment]
@menny done 😊

**Comment by paledega** [comment]
> @menny done 😊

@menny look pls

**Comment by menny** [comment]
@paledega can you rebase from the latest master and force push?

```
git pull --rebase upstream master
git push -f origin HEAD:Turkish
```

**Comment by paledega** [comment]
hmmm okay

**Comment by paledega** [comment]
done :D @menny is it okay

**Comment by menny** [comment]
this is pretty bad now...

**Comment by menny** [comment]
You'll need to close this PR and start a new one. Sorry about that, I just don't know what happened here.

**Comment by AnXh3L0** [comment]
@paledega can you please re-do a PR for this and use the current base? Something must have gone wrong and we can't merge this one in the current state :(

**Comment by menny** [comment]
Can someone else pick this up? I think this is an important change. @martholomew ?

**Comment by martholomew** [comment]
Sure

**Comment by martholomew** [comment]
Hey @paledega , could you link up the f keyboard xml here? Your repo is impossible to navigate, lol. Otherwise ill just recreate the f keyboard on swiftkey.

**Comment by martholomew** [comment]
Can be closed

**Pull request closed without merging**
