### PR TITLE
Add Belarusian pack

### PR DESCRIPTION
**Pull request by andrewshadura**
This is a language pack originally written by alex73, with hunspell-based dictionary and changed icon. I admit I haven't provided screenshots, but I don't think I'm able to provide good ones :)

### CODE REVIEW

**Comment by andrewshadura** [comment]
@menny, any news on this?

**Comment by menny** [comment]
It looks good. But I wonder how I can merge it into a new branch, and not _master_

**Comment by andrewshadura** [comment]
Any updates?

**Comment by rimas-kudelis** [comment]
@menny I think you should be able to create a new branch and then do the merging.

**Comment by menny** [comment]
@andrewshadura I'd love to merge this PR.
Want to rebase and update it to the latest Language-Pack structure?

**Comment by andrewshadura** [comment]
I'll try to.

**Comment by menny** [comment]
@friesenkiwi @andrewshadura what about this PR?

**Comment by friesenkiwi** [comment]
@menny I will try to salvage it, rebasing on master and make a new PR against the Belarusian branch

**Comment by friesenkiwi** [comment]
Rebased in #158

**Pull request closed without merging**
