### PR TITLE
Ukrainian uplift

### PR DESCRIPTION
**Pull request by menny**

### CODE REVIEW

**Comment by friesenkiwi** [comment]
So ... should I do something?
And what did you do differently? So I know for the next ones?

**Comment by menny** [comment]
I think this branch is quite broken, everytime we'll rebase it, we'll end up with conflicts.

I'll just publish this one. You can close your Ukraine PR

**Comment by menny** [comment]
updated at Play-Store

**Comment by menny** [comment]
fdroid: https://gitlab.com/fdroid/fdroiddata/merge_requests/2033

**Pull request merged**
