### PR TITLE
Add new greek dictionary.

### PR DESCRIPTION
**Pull request by algorithm314**
The aosp was removed because it had many wrong words.

### CODE REVIEW

**Comment by algorithm314** [comment]
I have not tried to build it, but after looking into [this](https://github.com/AnySoftKeyboard/LanguagePack/blob/master/buildSrc/src/main/java/MakeBinaryDictionary.java) file there is a 4MB hard limit for the dictionary. 24 bit offset minus 2 bits for flags = 22 bits = 4MB.

The proposed one is 7-8 MB with 362000 which is already constrained compared to other Greek dictionaries with 820000 words. Greek is a highly inflected language.

Should i make it half the size or maybe the offsets could be made 30 bits?

**Comment by menny** [comment]
I would suggest cutting it enough to make it work with the current limits, and open a ticket for me to increase the limit

**Comment by dim-geo** [comment]
Hi, is this 4MB limit fixed?
It's a problem for many dictionaries (I can't find the issues that mentioned it)
From my side it prevented me from using the keyboard.

In any case, if you can, please increase the limit to cover big dictionaries.

**Comment by martholomew** [comment]
moving to issue

**Pull request closed without merging**
