### PR TITLE
(resurrected) French

### PR DESCRIPTION
**Pull request by gmontcheuil**
Hello,

AnySoftKeyboard is a very great project. Thank you !
We start to use it because when a new device didn't allow enough languages...
Unfortunately the French language package was a little old and with some defects (it was very hard to type an apostrophe by example).

So I try to fix the problem.

Like said the README and whatsnew, this resurrected French branch offers: 
 * a [Dicolectte](https://www.dicollecte.org/home.php?prj=fr) based dictionary
 * two keyboard layout (AZERTY/QWERTY) with symbols, etc.

I followed the various steps of the README file, but **I didn't find the way to make screenshots** (sorry, it's the very first android project).
However I managed to build a debug APK that I test on my tablet, so it work at least on one android device ... and I hope on others with  AnySoftKeyboard installed ;-)

What next ?
Putting aside the screenshots, the dictionary could be greatly improved adding entries combining apostrophes and a word (b.e. determinant+noun: "l'enfant" or pronoun+verb: "c'est", "m'a"), but I don't know when I will have the time to do it - so perhaps it's better to not wait too much before to make a release.

### CODE REVIEW

**Comment by Lyokovic** [comment]
Hi,

I just tried to build and run your branch and it seems to work well on my device (both with the last ASK FDroid release and with a build from master).
I am using LineageOS 14.1 with microg on a OnePlus 3t.

Is something blocking with this PR? It would be great if it could be merged, the French package is not available on F-Droid anymore and has not been updated since 2011 on the play store :/

Thanks for your work ;)

**Comment by friesenkiwi** [comment]
Sorry for the long wait. Thank you very much for your contribution! I merge this now here and release as soon as possible!

**Comment by gmontcheuil** [comment]
Hello,

I see you just merged the changes...
  and I remember I haven't yet replied to your e-mail of January 31th.

On 31/01/18 11:10, Lyokovic wrote:
>
> Hi,
>
> I just tried to build and run your branch and it seems to work well on 
> my device (both with the last ASK FDroid release and with a build from 
> master).
> I am using LineageOS 14.1 with microg on a OnePlus 3t.
>
> Is something blocking with this PR?
>
As I said in my pull request, it's my 1st contribution to an android 
package...

The week-end I started to work on the french package, I just made the 
minimal configuration of the SDK to compile and generate an APK to test 
it on home devices but I have still some android-SDK concepts to learn 
for better testing, take screenshots and generate release APK.
Nevertheless I tried to follow the "development rules" described in the 
README.md, so I hope the merge was relatively easy.


> It would be great if it could be merged, the French package is not 
> available on F-Droid anymore and has not been updated since 2011 on 
> the play store :/
>
> Thanks for your work ;)
>

It's just a 1st step, I keep in mind the necessity of add apostrophes 
combinations as I mentioned in the pull request... perhaps for the Spring...

Grégoire

**Comment by milouse** [comment]
@gmontcheuil, can you confirm that you kept the BEPO layout in this version? That is one of the great features available in the old french layout and the alpha one available on #12. It's not clear reading you if you kept it or work only on an AZERTY layout.

**Comment by gmontcheuil** [comment]
@milouse NO, I didn't "kept" the BEPO layout, or to be more exact, I didn't grab it from the "old" French branch.
Many structural changes in the ASK's LanguagePack master branch wasn't yet applied to the French branch, so I preferred base my work on the master branch and follow the steps describe in the main README.

Steps 5 and 6 explain how to add/change keyboard layout. I followed them to add an AZERTY layout (very usual in France) and update the QWERTY one for a better access to accents and apostrophes.
I'm sorry that I didn't thought to the BEPO layout, but if the old "French" branch or any other recent branch have an adequate layout XML it is very easy to add it following this 2 steps.

**Comment by milouse** [comment]
Ok no problem, it was just to be sure. If I've time, I'll try to add it back as a pull request.

**Comment by menny** [comment]
@milouse, is is wise to release to branch to the Play Store?

**Comment by milouse** [comment]
Yes, an azerty layout is better than nothing. Bepo will come as an update when it'll be ready.

**Comment by menny** [comment]
I've added BÉPO. So that's done :)

@milouse what else is missing in the FR pack?

**Comment by milouse** [comment]
Wow, you've been really quick! Thank you very much. As this, I don't see what may be missing, but I'm not an expert too. I think the best is to release this new language pack asap and we'll test it in the wild. If something is missing, we'll see it at this moment.

**Comment by xavihernandez** [comment]
Hi there is no way to correct contracted words? Like _c'est_, _j'ai_, _l'école_, etc.? In most of keyboards it get corrected when you type _cest_, _jai_ or _lecole_ for example.

**Comment by gmontcheuil** [comment]
@xavihernandez
I know this problem and commented it in my pull request.

The Dicollecte Project changed their way to store entries with apostrophes.
Before they were stored as-is - so easy to retrieve -, but now you have to play with linguistic features and/or hunspell rules.

I haven't found the time to change that - perhaps this summer.
If someone is inspired, the Perl script is dictionary/dicollecte2wordlist.pl

**Comment by xavihernandez** [comment]
@gmontcheuil thanks for your answer. I have another question please: do you know why keyboard does not use frequency for word completion?
For instance, I'm French and use a lot the word _ça_, but when I type _ca_ it does not get corrected to _ça_, it's annoying to have to type on suggestions bar to select correct word while I always use it, and never use the first suggested.

**Comment by gmontcheuil** [comment]
@xavihernandez
I'm sorry but I didn't remember when and how the frequency appear in the code I changed.

You can eventually check if the wordlist generated by the Perl script had a high frequency for "ça" or not.
In it hasn't, it's something to correct/add in the script.
Otherwise it could be a problem more generic to AnySoftKeyboard and I recommend you to open a new thread.

**Pull request merged**
