### PR TITLE
Lithuanian keyboard pack

### PR DESCRIPTION
**Pull request by rimas-kudelis**
(This is a clone of #16)

This is based on the original Lithuanian pack still available on Google Play, but vastly expanded.
In addition to the original three-row QWERTY layout, this pack now also ships:
- four-row QWERTY-based layout (similar to the default layout on all PCs) – I chose this to be the default Lithuanian layout (first one in the list and having no qualifiers in its name)
- three-row ĄŽERTY-based layout (similar to the official Lithuanian standard keyboard)
- 16-key vertical layout (which switches to the the aforementioned four-row layout in landscape mode)

I have also cleaned up some files which are generated at compile time and added them to .gitignore.

On top of all that, I am adding a crowd-sourced autocorrection dictionary. That one needs some reviewing, but I think it should be a good start.

The screenshots under StoreStuff were taken on my Samsung Galaxy S2 phone. I couldn't find the theme that was used for the original screenshots, so the ones I made are quite dark and might need to be re-taken.

### CODE REVIEW

**Comment by rimas-kudelis** [comment]
@menny, @herrlado: Once this is merged, I would love if you could release a new version of [this pack](https://play.google.com/store/apps/details?id=org.herrlado.ask.languagepack.lithuanian) on Google Play.

**Comment by menny** [comment]
it is now merged.
I can release this, but it will not overwrite @herrlado's language pack.

@herrlado can you clone and release this?

**Comment by rimas-kudelis** [comment]
Is it not possible to transfer ownership of a package on Play?

**Comment by menny** [comment]
It is possible. Do you want to take ownership from @herrlado?

I can take it, if you can't and Lado is retiring 😃

**Comment by rimas-kudelis** [comment]
I guess I'd rather you take it over. :)

**Comment by herrlado** [comment]
It is possible, @rimas-kudelis  would you like to?

**Comment by rimas-kudelis** [comment]
I could become the maintainer of this, but I'm not really using ASK, since I bought myself a Swype license a couple years ago and got reaaaaally used to swiping all the things. :)

Plus I have no idea how to sign a package (yet).

**Comment by rimas-kudelis** [comment]
Either way, please pull in #18 as well before releasing. Thanks!

**Comment by herrlado** [comment]
ok, no problem, I can release it on play store!

**Comment by rimas-kudelis** [comment]
Hm, is it perhaps possible to share ownership of the package? I'd be fine with being its "backup owner". 🙂

**Comment by herrlado** [comment]
I think it is possible to let you admin the play store entry, so change text, images etc. I will check this

**Comment by herrlado** [comment]
what is your google email?

**Comment by rimas-kudelis** [comment]
it's rimmas

**Comment by herrlado** [comment]
so rimmas@gmail.com ?

**Comment by rimas-kudelis** [comment]
yes :)

**Comment by herrlado** [comment]
please check if you can see the store entry.

**Comment by rimas-kudelis** [comment]
Wow, do I really have to pay $25 just to register myself as a developer on Play Store?

**Comment by herrlado** [comment]
:( yes. But once you have done it, it's life time. On app store people pay 100$/year

**Comment by rimas-kudelis** [comment]
Right. Well I'll pass for now, but will keep that in mind.

**Comment by rimas-kudelis** [comment]
@herrlado so could you release an update?

**Comment by herrlado** [comment]
Does it have a dictionary? I can not build the package,

```
Error:Execution failed for task ':makeDictionary'.
> java.io.FileNotFoundException: /home/lado/development/android/ask/LanguagePack/src/main/res/raw/words_1.dict (No such file or directory)
```

**Comment by herrlado** [comment]
We need to publish it also  

Screenshots, how it looks like on a 7'' and 10'' tablet.

Also a graphic 512 x 512 and  1024 x 500

**Comment by rimas-kudelis** [comment]
I added `/src/main/res/raw/ ` to `.gitignore`, but that directory is required for the build to be successful. I actually wanted to commit it with an empty `.gitkeep` file, but I must have missed the fact that the file wasn't added to git. If you create that dir, the build will succeed.

Regarding screenshots: I only have Android smartphones at home, no tablets. Are these screenshots required? Also, what kind of graphics do you need for 512x512 and 1024x500? These images don't seem to exist in master.

**Comment by rimas-kudelis** [comment]
@herrlado  ↑

**Comment by herrlado** [comment]
So, do we have new dictionary? I can not build the application. I can organize screenshots or fake them, if it you can not provide them, but how can I build the app?

**Comment by rimas-kudelis** [comment]
@herrlado The dictionary is being built during compile time. The real issue is that the directory into which it should be built did not exist in my branch due to my oversight. I've addressed that in my previous comment and in #19.

Regarding the screenshots, kindly please create them if you can.

**Comment by rimas-kudelis** [comment]
...or at least that is my understanding (re dictionaries).

**Comment by herrlado** [comment]
ok, let's try.

**Comment by herrlado** [comment]
I've send you the release apk. Please test it.

**Comment by rimas-kudelis** [comment]
Yep, seems to work fine.
I had also tested my own debug builds before, and they worked as well.

**Comment by rimas-kudelis** [comment]
@herrlado are you still waiting for something?

**Comment by herrlado** [comment]
Will be there in a couple of hour. I have just deployed it there. If you have a translation for the description or another description i can put it also there.

**Comment by rimas-kudelis** [comment]
Thanks! Here's a description:

> Lietuviški išdėstymai ir žodynai „AnySoftKeyboard“ klaviatūrai.
> 
> Tai – „AnySoftKeyboard“ klaviatūrai skirtas plėtinys.
> Prieš jį diegdami, įdiekite „AnySoftKeyboard“ klaviatūrą. Tai atlikę, galėsite pasirinkti norimus išdėstymus „AnySoftKeyboard“ nustatymuose pasirinkdami meniu punktą „Klaviatūros“.

I also would suggest to slightly change the English description as follows (this basically swaps singular and plural occurences of the word "layout"):

> Lithuanian layouts and wordlist for AnySoftKeyboard.
> 
> This is an expansion layout pack for AnySoftKeyboard.
> Install AnySoftKeyboard first, and then select the desired layout from AnySoftKeyboard's Settings->Keyboards menu.

**Comment by herrlado** [comment]
I Need also title 30 Chars

**Comment by rimas-kudelis** [comment]
AnySoftKeyboard – lietuvių kalbos paketas

**Comment by herrlado** [comment]
It has length 41, we need as title only 30

**Comment by rimas-kudelis** [comment]
ouch, sorry. Let's make it as follows then:
AnySoftKeyboard – lietuvių k.

**Comment by herrlado** [comment]
yes, thanks. Done!

**Comment by rimas-kudelis** [comment]
Awww, you've changed the title, and now it looks like machine translated. :) The 30-char requirement certainly doesn't make it easy to write a good one, but I believe mine was better.

Also, what about other screenshots? I'd really like the users to know right away that this pack contains multiple layouts. Would you please upload other images as well?

**Comment by rimas-kudelis** [comment]
And you somehow deleted the first line of the description. Since the title isn't long enough to be descriptive, that first line should stay in the description.

**Comment by herrlado** [comment]
Done :)

**Comment by rimas-kudelis** [comment]
Can you also replace the word "plėtinys" with "priedas"? I think this will sound more natural. Sorry for nagging you like this by the way. :)

**Comment by herrlado** [comment]
It's fine!

**Comment by rimas-kudelis** [comment]
thank you once again! :)

**Comment by rimas-kudelis** [comment]
@herrlado care to change the title to my version(`AnySoftKeyboard – lietuvių k.`)  as well? :) I really think that one was better.

**Comment by herrlado** [comment]
But title in english should be english, or not? For Lithuanian language I have the title in Lithuanian.

**Comment by rimas-kudelis** [comment]
I meant the Lithuanian title. The one I currently see says "AnySoftKeyboard - Lietuviški", which is suboptimal.

**Comment by herrlado** [comment]
a ok, missed that. Ok changed.

**Comment by rimas-kudelis** [comment]
Thanks!

**Comment by Baltix** [comment]
@rimas-kudelis , @menny , @herrlado , Thank You very much :)

**Comment by zledas** [comment]
I guess this is gone from Google Play now?

**Comment by rimas-kudelis** [comment]
@ziedas It is, for now at least. You can still find the APK on some other sites though.
I've pinged https://gitter.im/AnySoftKeyboard/localization about this again, but it's not the first time that I have, and it's possible the ping will again end up unnoticed and not acted upon.

The sources are still on git however, so all it takes is for someone with a Play developer account and enough motivation to actually build the package and upload it.

**Comment by menny** [comment]
I never owned this package. I'm sorry. I'm willing to take ownership on it, and move all its code to ASK official repo.

**Comment by menny** [comment]
Wait. I do have the code at https://github.com/AnySoftKeyboard/LanguagePack/tree/Lithuanian

**Comment by menny** [comment]
But I do not own the app in the Play-Store (id org.herrlado.ask.languagepack.lithuanian)

**Comment by rimas-kudelis** [comment]
Yeah. I wonder what we could do about it. Looking at the discussion above, it seems @herrlado actually made me a co-owner, or at least tried to, but I didn't have a GPC account, and still don't. I could pay the $25 fee, but I wonder if that invitation will still be there. Any idea if they expire?

**Comment by menny** [comment]
I don't know if it expires.

Another option - since I have the source code - is to publish the pack under a different app-id. This means that if you already have the pack installed you will not be updated, but new installs will work just fine.

**Comment by rimas-kudelis** [comment]
Well, my curiosity got the best of me and I registered. But I don't see Lado's app either. :(

**Comment by rimas-kudelis** [comment]
So unless we can still reach him, I guess the app is lost?

**Comment by rimas-kudelis** [comment]
@menny I'll try shooting Lado an email and see if he answers. If not, let's go with your option then. Is that okay?

**Comment by menny** [comment]
yes. np. I can also take ownership of the pack, if @herrlado wants.

**Comment by rimas-kudelis** [comment]
The package is back!
I guess it would be best if we both had the rights to maintain it. Do you know if that is possible?

**Comment by menny** [comment]
Can you paste the link to the pack?

**Comment by rimas-kudelis** [comment]
It's https://play.google.com/store/apps/details?id=org.herrlado.ask.languagepack.lithuanian, just like it used to be.

**Comment by rimas-kudelis** [comment]
@menny is there a separate issue about merging language pack branches to the main branch? It seems your current plan is to merge all packs into a single branch, and I applaud that, but I wonder why it hasn't been fully done yet.

**Comment by zledas** [comment]
Thanks for looking into this!

This is my first Android so I am not sure what keyboard I will choose in the end (trying out a few now, and I don't like height of the LT buttons currently :) ), but you could add me as a developer as well (I have an account and am quite experienced, tho more with game development than native): zilvinas (dot) ledas (at) dict (dot) lt

**Comment by rimas-kudelis** [comment]
@ziedas just FYI: there are themes with somewhat different button heights, and you can disable some bits of the top/bottom rows in ASK settings.

**Comment by menny** [comment]
@zledas you can also override the height of keys. In the Themes->Tweaks section you can specify a height factor.

**Comment by zledas** [comment]
Thanks, looks like I missed some options!

**Comment by rimas-kudelis** [comment]
@zledas 
> (trying out a few now, and I don't like height of the LT buttons currently :) )

I've released a new beta update on Google Play, which increases key height in the default lt layout (https://github.com/AnySoftKeyboard/LanguagePack/pull/256). Feel free to test it if you don't mind. ;)

**Pull request merged**
