### PR TITLE
Afrikaans

### PR DESCRIPTION
**Pull request by markwmuller**
Adding Afrikaans language pack

### CODE REVIEW

**Comment by markwmuller** [comment]
@menny  Follow up on this PR. I realized I omitted adding an assignee.

**Comment by friesenkiwi** [comment]
Thank you for your contribution! I will try to release as soon as possible!

**Comment by menny** [comment]
@markwmuller are you publishing this package?

**Comment by markwmuller** [comment]
I wasn't planning on publishing myself, I thought that it would get pushed out with the rest of the ASK languages. If that's not the case, what do I do? I have no desire to publish myself, if it can be outsourced :)

**Comment by menny** [comment]
@markwmuller I was planning on creating Afrikaans on Play-Store, but it won't allow me, as if someone else already created that pack.

Do you have any idea who?

**Comment by markwmuller** [comment]
Wasn't me :) I think there used to be an Afrikaans language pack, back in the day, but I don't know the story/status.

**Comment by menny** [comment]
Okay.. I'll used a different application-ID

**Comment by menny** [comment]
thanks!

**Pull request merged**
