### PR TITLE
Dutch

### PR DESCRIPTION
**Pull request by SvGeloven**
Closes https://github.com/OpenTaal/LanguagePack/issues/1

### CODE REVIEW

**Comment by SvGeloven** [comment]
Let me know when this has been merged so I can make a merge request at fdroiddata to trigger a build there. I would like to keep this extra step here so maintainers of LanguagePack repo act as a double check.

**Comment by friesenkiwi** [comment]
Only out of interest: What are the considerations of changing the wording in the license from "allowed" to "intended"? And why is it restricted anyways?

**Comment by SvGeloven** [comment]
The 'allowed' didn't hold up with the license, so that was incorrect wording. The list is truncated because of the 4 MB limitations of ASK's binary tree that holds the data. People should not use this list for other purposes. Furthermore, the frequency has been scaled to match ASK's requirements. Should I mention that? I got some more questions on this.

**Comment by friesenkiwi** [comment]
Ahm so the underlying list is still free?
Yes, I think, it would be a good idea to mention it e.g., in the README (while checking https://github.com/OpenTaal/LanguagePack/blob/Dutch/LICENSE I noticed that on the top it is mentioned that it is licensed under BSD and CC, but below fulltexts are MIT and BSD...?)
I mean, it doesn't hurt and there's space enough to mention ;-)

**Comment by SvGeloven** [comment]
Good one, will correct that too.

**Pull request merged**
