### PR TITLE
Added Bulgarian

### PR DESCRIPTION
**Pull request by martholomew**
Made keyboards, dictionary from [here](https://github.com/LineageOS/android_packages_inputmethods_LatinIME/blob/lineage-16.0/dictionaries/bg_wordlist.combined.gz).
Same as [this](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.bulgarian&hl=en_US).

### CODE REVIEW

**Comment by martholomew** [comment]
By the way, I saw on my other pull requests that you added screenshots and native titles/descriptions for the play store after they were merged, would it be helpful for me to add those on subsequent pull requests?

**Comment by menny** [comment]
If you can add those in your original PR, that would be great.

If the PR does not contain screenshots, I take the old screenshots from the Play Store.

**Comment by martholomew** [comment]
I've added screenshots and added more to the description.

**Comment by menny** [comment]
thanks!

**Pull request merged**
