### PR TITLE
Danish

### PR DESCRIPTION
**Pull request by friesenkiwi**
Merged latest master, cleaned up and switched to AOSP dictionary

### CODE REVIEW

**Comment by menny** [comment]
Published to Play-Store.

**Comment by menny** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2147

**Comment by menny** [comment]
@friesenkiwi one of the comments on the Danish pack says "Missing even the simples words in Danish."

Any ideas?

**Comment by friesenkiwi** [comment]
@ menny Huh, not really, no sorry, my generated words_from_aosp.xml has 178450 words and includes words with the danish special letters ø,å, æ (both upper and lower case). Is the ASK main app accessing and suggesting them?
Unfortunately I can't see the danish comments/reviews at https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.danish.

**Pull request merged**
