### PR TITLE
Kabyle language pack

### PR DESCRIPTION
**Pull request by BoFFire**
String Kabyle language pack

### CODE REVIEW

**Comment by menny** [comment]
This is a good start.
A few missing things:
1. icon for the pack. Should replace https://github.com/BoFFire/LanguagePack/blob/d60cb9acc7625ae51e3868e1f533d6b6edafe03e/src/main/res/drawable-xhdpi/app_icon.png
2. a flag icon
3. Update the store-graphics. Should replace the files at https://github.com/BoFFire/LanguagePack/tree/d60cb9acc7625ae51e3868e1f533d6b6edafe03e/StoreStuff

What about a dictionary?

**Comment by BoFFire** [comment]
Updating Kabyle layout

**Comment by BoFFire** [comment]
@menny can we betatest this first. Graphics and dictionnary (kab.Wikipedia.org)  will come soon :)

**Comment by BoFFire** [comment]
Test via: https://twitter.com/BoFFire/status/838087462006173697

**Pull request closed without merging**
