### PR TITLE
Czech Language Pack

### PR DESCRIPTION
**Pull request by friesenkiwi**
As requested by @knezi.
Salvaging the changes and fixes made by @lubekgc at https://github.com/lubekgc/AnySoftKeyboard-LanguagePack/tree/Czech-fixes, also closing #6, https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/359.
Probably @herrlado will need to release the resulting Pack to Play Store? Or would it be reasonable to transfer the ownership like done with the Russian pack?

### CODE REVIEW

**Comment by herrlado** [comment]
Hey. I would prefere to transfer the ownership to a new maintainer. What
do we need for that?


herrlado

**Comment by friesenkiwi** [comment]
I can't speak  for @menny, he needs to decide on that. But if he were to accept the ownership, it would probably go something along the lines of how it was done with the Russian at https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/690#issuecomment-279278464...?

**Comment by friesenkiwi** [comment]
Hey @herrlado 
@menny is ready to accept ownership of org.herrlado.ask.languagepack.czech. Can you do the necessary steps in your Play account?

**Comment by herrlado** [comment]
Sure.

What can I do? @menny?


Lado

**Comment by menny** [comment]
@herrlado I'll email you for details.

**Comment by menny** [comment]
@herrlado @friesenkiwi the Czech package was transferred to my account. Thank you.

**Comment by friesenkiwi** [comment]
OK, great, so I will merge and release to F-Droid soon and we will try the automated Play Store deployment on this and see how it goes.

**Pull request merged**
