### PR TITLE
Dutch

### PR DESCRIPTION
**Pull request by SvGeloven**
Please use this version for upstream merge which has been tested. Also review the changes if you like. We will upload APK to Google Play and F-Droid ourselves.

### CODE REVIEW

**Comment by menny** [comment]
Should I unpublish the Dutch pack in the Play Store?

**Comment by SvGeloven** [comment]
I didn't know it was already in the Google Play. Do you have a link for that, since I cannot find it.

Meanwhile, I have also bumped the version numbers and made some small improvements. So another pull request will follow soon.

**Comment by menny** [comment]
I unpublished it. It only included a simple dictionary and no layouts. I prefer if you can publish under your account

**Comment by SvGeloven** [comment]
Meanwhile it has a custom layout and later more. If you still prefer I will publish it myself.

Nevertheless, will keep doing pull requests as the repo I use is for development and testing and the version here is the original one. That still okay? Also for F-Droid to get their source code. Do you know who does the build for F-Droid for AnySoftKeyboard?

**Comment by menny** [comment]
Yes, please publish yourself.

I'm usually doing the AnySoftKeyboard main app pushes to fdroid. Do you know what's the status of fdroid? Now that krt is leaving

**Comment by SvGeloven** [comment]
Will publish self. No problem.

Yes, I am also partly active in that community. For packaging and upgrading apps it is business as usual, luckily.

Do you also push Language packs to F-Droid or should I also do that myself?

**Comment by menny** [comment]
Please, publish at f-droid as well. I'm very slow with publishing stuff, and it hurts the users. IF you can take on that, it would be awesome.

if you can, please join https://gitter.im/AnySoftKeyboard/fdroid
also @friesenkiwi ^^

**Comment by SvGeloven** [comment]
I get this error at the moment:

    Upload failed
    
    You need to use a different package name because "com.anysoftkeyboard.languagepack.dutch" already exists in Google Play.

Please unpublish and remove all related APK files for this language pack from Google Play. Thanks.

**Comment by SvGeloven** [comment]
Second question, could you please mer from https://github.com/OpenTaal/LanguagePack/tree/Dutch up until (and including) the latest commit https://github.com/OpenTaal/LanguagePack/commit/f4205f92aafedf34fa8dd337dce0bd549a789b93 and close this pull request. When that is done I can let F-Droid start packaging and building.

**Comment by friesenkiwi** [comment]
OK, I merged it (see https://github.com/AnySoftKeyboard/LanguagePack/commit/88ac50b5eb57aaf00463550e48fe380393740b91)
So, everything is latest and you can push to F-Droid? :-)
Judging from Gitter, the Play Store issue is solved as well?

**Comment by SvGeloven** [comment]
There is another commit on its way, so please wait until that with f-droid.

**Comment by SvGeloven** [comment]
and the issues with google play is also not fixed yet

**Comment by friesenkiwi** [comment]
OK, so, for the record:

- [ ] Merge another commit
- [ ] @SvGeloven publishes to F-Droid 
- [ ] Transfer ownership of com.anysoftkeyboard.languagepack.dutch on Play Store

**Comment by menny** [comment]
Seems right

**Comment by SvGeloven** [comment]
please, split the second item to:
- svgeloven update f-droid metadata
- friesenkiwi published on f-droid (it has already been packages but manually excluded from the build)

**Comment by PanderMusubi** [comment]
see:
1. latest commits in https://github.com/AnySoftKeyboard/LanguagePack/pull/83
2. awaiting merge at fdroid
3. to do
4. ongoing

**Pull request merged**
