### PR TITLE
Add Basque Language Pack

### PR DESCRIPTION
**Pull request by aldatsa**
Hi,
we have created a Basque language pack for AnySoftKeyboard. It would be great if you could merge it to your project and release it in the Play Store.

Let me know if there are any problems.

This is the title and description for the Play Store in English and Basque:

----------------------------------------------

Basque Language pack

Features:
- Basque dictionary with more than 100,000 words that includes words from unified Standard Basque and from the Biscayan dialect. [1]
- Includes the ñ key.
- Includes the zero-width space key (a.k.a. "datraolat"). Long press the d key to use it. Useful for adding suffixes to hashtags in Twitter, Instagram...

This is an expansion language pack for AnySoftKeyboard.
Install AnySoftKeyboard first, and then select the Basque keyboard from AnySoftKeyboard's Settings -> Languages -> Keyboards menu.

[1] Note: It's based on the dictionary created by Igor Leturia for FirefoxOS. We filtered the dictionary using the spell checkers Xuxen (Standard Basque) and Xuxen B (Biscayan dialect).

----------------------------------------------

Euskarazko hizkuntza paketea

Ezaugarriak:
- Euskara Batua eta Bizkaierazko 100.000 hitz baino gehiago dituen euskarazko hiztegia. [1]
- ñ tekla dauka.
- Zero zabalerako zuriunea tekla ("datraolat" bezala ezaguna) dauka. d tekla sakatuta edukita erabil daiteke. Erabilgarria Twitter, Instagram... eta abarretan traolei atzizkiak gehitzeko.

Hau AnySoftKeyboard-entzako hizkuntza pakete osagarri bat da.
Instalatu AnySoftKeyboard lehenik eta ondoren hautatu Euskarazko teklatua AnySoftKeyboard-en Ezarpenak -> Hizkuntzak -> Teklatuak menuan.

[1] Oharra: Igor Leturiak FirefoxOSrentzat sortutako hiztegian oinarritua dago. Xuxen (Batua) eta Xuxen B (Bizkaiera) zuzentzaile ortografikoak erabiliz iragazi dugu hiztegia.

### CODE REVIEW

**Comment by menny** [comment]
I've publish to Play-Store. It should be available in a couple of hours.
I've also created a MR for F-Droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/2008

**Comment by menny** [comment]
@aldatsa where did you get the base for your https://github.com/AnySoftKeyboard/LanguagePack/pull/34/files#diff-a3af4ee127757c74895206fa8a588a05 ?
Seems that Google thinks this is based on an icon owned by "Magyar AnySoftKeyboard APK logo".
They have rejected the language-pack and will not publish it.

It is already available in f-droid.

**Comment by aldatsa** [comment]
A member from our team is creating a new icon. Should I create a new PR when it's ready?

**Comment by menny** [comment]
@aldatsa yes, please.

Thank you for the quick response. While on the subject of Basque, did you see my comments on https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/887

**Pull request merged**
