### PR TITLE
Reorganize popupCharacters of 'e' for a better user comfort

### PR DESCRIPTION
**Pull request by Erwan-S**
Reorganize popupCharacters of 'e' for a better user comfort

### CODE REVIEW

**Comment by menny** [comment]
thank you @Erwan-S, can you add a comment in the XML file why this is a better arrangement?

**Comment by Erwan-S** [comment]
The need to re-organize the characters is due to the change in the positioning of the pop-up, itself caused by the addition of the 7th character. 

On second thought, it seems to me more coherent to keep the current order but to remove the 'é' character. This one being directly accessible in Bépo, it is redundant in this list and the reversion to 6 characters would restore the previous positioning of the pop-up and therefore the convenience of the current order

**Comment by menny** [comment]
@Erwan-S, thanks for taking another look. what do you suggest doing with this PR?

**Comment by Erwan-S** [comment]
> 
> 
> @Erwan-S, thanks for taking another look. what do you suggest doing with this PR?

I force-updated accordly. Would you prefer that I decline it and create a new one ?

**Comment by menny** [comment]
thanks

**Pull request merged**
